select min(parcel_number), max(parcel_number), count(parcel_number) from "MonthlyTax";
select min("PARCELID"), max("PARCELID"), count("PARCELID") from "BuildingInfo";

select distinct "PARCELID" from "BuildingInfo" except (select distinct parcel_number from "MonthlyTax" where prop_class_code = 510);
(select distinct parcel_number from "MonthlyTax" where prop_class_code = 510) except select distinct "PARCELID" from "BuildingInfo";
(select distinct parcel_number from "MonthlyTax" where prop_class_code = 510) intersect select distinct "PARCELID" from "BuildingInfo";

with subset(
        parcel_number             ,
        "2_5_flag"                ,
        homestead_flag            ,
        book                      ,
        page                      ,
        property_id               ,
        mltown                    ,
        prop_class_code           ,
        class_description         ,
        appraisal_area            ,
        area_description          ,
        owner_name_1              ,
        owner_name_2              ,
        owner_address_1           ,
        owner_address_2           ,
        owner_city                ,
        owner_state               ,
        owner_zip                 ,
        location_house_number     ,
        location_street_direction ,
        location_street_name      ,
        location_street_suffix    ,
        location_city             ,
        location_state            ,
        location_zip              ,
        mailing_name_1            ,
        mailing_name_2            ,
        mailing_address_1         ,
        mailing_address_2         ,
        mailing_city              ,
        mailing_state             ,
        mailing_zip               ,
        property_description      ,
        divided_flag              ,
        new_construction_flag     ,
        spec_assess_flag          ,
        school_district           ,
        school_district_desc      ,
        tax_district              ,
        tax_district_desc         ,
        foreclosure_flag          ,
        deeded_acreage            ,
        rental_registration_flag  ,
        bor_flag                  ,
        transfer_date             ,
        sale_amount               ,
        num_parcels               ,
        conveyance_number         ,
        deed_number               ,
        sale_source               ,
        sale_type                 ,
        previous_owner_name_1     ,
        previous_owner_name_2     ,
        ag_use                    ,
        market_land_value         ,
        market_impr_value         ,
        total_market_value        ,
        annual_taxes              ,
        annual_taxes_paid         ,
        delinquent_taxes          ,
        delinquent_taxes_paid     ,
        active_flag               ,
        initial_sale_price
    ) as (
        select
            parcel_number             ,
            "2_5_flag"                ,
            homestead_flag            ,
            book                      ,
            page                      ,
            property_id               ,
            mltown                    ,
            prop_class_code           ,
            class_description         ,
            appraisal_area            ,
            area_description          ,
            owner_name_1              ,
            owner_name_2              ,
            owner_address_1           ,
            owner_address_2           ,
            owner_city                ,
            owner_state               ,
            owner_zip                 ,
            location_house_number     ,
            location_street_direction ,
            location_street_name      ,
            location_street_suffix    ,
            location_city             ,
            location_state            ,
            location_zip              ,
            mailing_name_1            ,
            mailing_name_2            ,
            mailing_address_1         ,
            mailing_address_2         ,
            mailing_city              ,
            mailing_state             ,
            mailing_zip               ,
            property_description      ,
            divided_flag              ,
            new_construction_flag     ,
            spec_assess_flag          ,
            school_district           ,
            school_district_desc      ,
            tax_district              ,
            tax_district_desc         ,
            foreclosure_flag          ,
            deeded_acreage            ,
            rental_registration_flag  ,
            bor_flag                  ,
            transfer_date             ,
            sale_amount               ,
            num_parcels               ,
            conveyance_number         ,
            deed_number               ,
            sale_source               ,
            sale_type                 ,
            previous_owner_name_1     ,
            previous_owner_name_2     ,
            ag_use                    ,
            market_land_value         ,
            market_impr_value         ,
            total_market_value        ,
            annual_taxes              ,
            annual_taxes_paid         ,
            delinquent_taxes          ,
            delinquent_taxes_paid     ,
            active_flag               ,
            null::bigint as initial_land_value,
            null::bigint as initial_building_value
        from "MonthlyTax"
        where prop_class_code = 510
        order by random()
        limit 200)
    select *
        into OCRTargets
        from subset
        left join "BuildingInfo"
        on parcel_number = "PARCELID"
        order by parcel_number;